In [146]:
import numpy as np
import pandas as pd

# DataType & Attributes

In [96]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [97]:
type(a1)

numpy.ndarray

In [98]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [99]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [100]:
a1.shape

(3,)

In [101]:
a2.shape

(2, 3)

In [102]:
a3.shape


(3, 2, 3)

In [103]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [104]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [105]:
#Create a DataFrame from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Createing arrays

In [106]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [107]:
sample_array.dtype

dtype('int32')

In [108]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
one.dtype

dtype('float64')

In [110]:
type(one)

numpy.ndarray

In [111]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [113]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [114]:
np.random.random((5,3))

array([[0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672]])

In [115]:
#Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing array and metrics

In [116]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [118]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [119]:
#get the first 4 number of the inner most array 
a4[:,:,:2,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6]]]])

## Manipulating and & Comparing arrays

### Arithmetic

In [120]:
a1

array([1, 2, 3])

In [121]:
ones = np.ones(3)

In [122]:
a1+ones

array([2., 3., 4.])

In [123]:
a1-ones

array([0., 1., 2.])

In [124]:
a1*ones

array([1., 2., 3.])

In [125]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [126]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [127]:
a3 = np.random.randint(1,50,size=(2,3,3))
a3.shape

(2, 3, 3)

In [128]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [129]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [130]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [131]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape * a3

array([[[ 41. ,  14. ,  31. ],
        [ 50. ,   6. ,   8. ],
        [102.3, 115.5, 145.2]],

       [[ 56. , 196. , 164. ],
        [ 45. , 100. , 160. ],
        [ 58.5, 175.5,  19.5]]])

Transpose = switch the axis

In [132]:
a2.shape

(2, 3)

In [133]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [134]:
a2.T.shape

(3, 2)

## Dot product

In [135]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [136]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [137]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [138]:
# Dot product
np.dot(mat1,mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Aggregation

In [139]:
a1

array([1, 2, 3])

Use Python's methods(`sum()`) on Python datatype and use Numpy's methods (`np.sum()`) on NumPy arrays

In [140]:
massive_array = np.random.random(1000)


In [141]:
%timeit sum(massive_array) # Python's Sum()
%timeit np.sum(massive_array)

124 µs ± 2.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
3.29 µs ± 7.73 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Dot product Example

In [145]:
#Number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [148]:
weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ['Mon', 'Tues', 'Wed', 'Thurs','Fri'],
                           columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [149]:
#Create prices array
price = np.array([10,8,12])
price

array([10,  8, 12])

In [157]:
price.reshape(1,3)

array([[10,  8, 12]])

In [158]:
#Create butter_prices DataFrame
butter_prices = pd.DataFrame(price.reshape(1,3),
                             index = ['Price'],
                             columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [161]:
price.T.shape

(3,)

In [160]:
np.dot(sales_amounts,price.T)

array([240, 138, 458, 232, 142])

In [162]:
#Create daily_sales column
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [163]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [164]:
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [169]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [173]:
weekly_sales['Total'] = daily_sales.T
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

## Comparision Operator

In [174]:
a1

array([1, 2, 3])

In [175]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [176]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [178]:
bool_array = a1 >= a2

In [179]:
type(bool_array)

numpy.ndarray

## Sorting array

In [181]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [182]:
random_array.shape

(3, 5)

In [183]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [184]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [185]:
a1

array([1, 2, 3])

In [186]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [187]:
np.argmin(a1)

0

In [188]:
np.argmax(a1)

2

In [192]:
np.argmax(random_array,axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [191]:
np.argmax(random_array,axis=1)

array([4, 1, 1], dtype=int64)

## Practical Example

<img src="Resources/zero-to-mastery-ml-master/images/numpy-panda.png"/>

In [197]:
# Turn an image into an NumPy array
from matplotlib.image import imread
panda =imread('Resources/zero-to-mastery-ml-master/images/numpy-panda.png')
type(panda)

numpy.ndarray

In [200]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

array([[0.05098039, 0.10196079, 0.0627451 ],
       [0.05098039, 0.10196079, 0.0627451 ],
       [0.05098039, 0.10196079, 0.0627451 ],
       ...,
       [0.17254902, 0.13725491, 0.10196079],
       [0.17254902, 0.13725491, 0.10196079],
       [0.17254902, 0.13725491, 0.10196079]], dtype=float32)