In [1]:
import numpy as np

# DataType & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape


(3, 2, 3)

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [11]:
#Create a DataFrame from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Createing arrays

In [12]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [13]:
sample_array.dtype

dtype('int32')

In [14]:
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
one.dtype

dtype('float64')

In [16]:
type(one)

numpy.ndarray

In [17]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [19]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 3, 0, 5, 1],
       [3, 9, 9, 6, 4],
       [3, 8, 8, 1, 6]])

In [20]:
np.random.random((5,3))

array([[0.42776205, 0.59187038, 0.88158016],
       [0.01356275, 0.1553255 , 0.00972253],
       [0.27675817, 0.71633517, 0.71633567],
       [0.42793521, 0.28544735, 0.11695614],
       [0.27409506, 0.93531185, 0.33066447]])

In [21]:
#Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing array and metrics

In [22]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [24]:
a4.shape,a4.ndim

((2, 3, 4, 5), 4)

In [25]:
#get the first 4 number of the inner most array 
a4[:,:,:2,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6]]]])

## Manipulating and & Comparing arrays

### Arithmetic

In [26]:
a1

array([1, 2, 3])

In [27]:
ones = np.ones(3)

In [28]:
a1+ones

array([2., 3., 4.])

In [29]:
a1-ones

array([0., 1., 2.])

In [30]:
a1*ones

array([1., 2., 3.])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [35]:
a3 = np.random.randint(1,50,size=(2,3,3))
a3.shape


(2, 3, 3)

## Aggregation

In [36]:
a1

array([1, 2, 3])

Use Python's methods(`sum()`) on Python datatype and use Numpy's methods (`np.sum()`) on NumPy arrays

In [40]:
massive_array = np.random.random(1000000)


In [41]:
%timeit sum(massive_array) # Python's Sum()
%timeit np.sum(massive_array)

125 ms ± 4.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
431 µs ± 24.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
