# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [275]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [276]:
# Create a 1-dimensional NumPy array using np.array()
oned_array = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
twod_array = np.array([[1,2,3],
                   [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
threed_array = np.array([[[1,2,3],
                   [4,5,6]],
                    [[7,8,9],
                   [10,11,12]]])
oned_array.ndim,twod_array.ndim,threed_array.ndim

(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [277]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
oned_array.shape,oned_array.ndim,oned_array.dtype,oned_array.size,type(oned_array)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [278]:
# Attributes of 2-dimensional array
twod_array.shape,twod_array.ndim,twod_array.dtype,twod_array.size,type(twod_array)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [279]:
# Attributes of 3-dimensional array
threed_array.shape,threed_array.ndim,threed_array.dtype,threed_array.size,type(threed_array)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [280]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame(twod_array)

0  1  2
0  1  2  3
1  4  5  6

In [281]:
# Create an array of shape (10, 2) with only ones
one_array = np.ones((10,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [282]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7,2,3))
zeros_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [283]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [284]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(low=0,high=10,size=(7,2))
random_array

array([[9, 6],
       [8, 6],
       [0, 0],
       [8, 8],
       [3, 8],
       [2, 6],
       [5, 7]])

In [285]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_random_array = np.random.uniform(low=0,high=1,size=(3,5))
float_random_array

array([[0.53408942, 0.48482997, 0.69243603, 0.26941233, 0.24412552],
       [0.16829104, 0.21876422, 0.558102  , 0.40383617, 0.06489225],
       [0.25391541, 0.24687606, 0.69630427, 0.71227059, 0.14808693]])

In [286]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(low=0,high=10,size=(4,6))
random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [287]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(low=0,high=10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [288]:
# Find the 0'th index of the latest array you created


In [289]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [290]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [291]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2,:2]

array([[8, 0],
       [2, 4]])

In [292]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(low=0,high=10,size=(3,5))
one_array = np.ones((3,5))

In [293]:
# Add the two arrays together
sumed_array = random_array+one_array

In [294]:
# Create another array of ones of shape (5, 3)
one_array_2 = np.ones((5,3))

In [295]:
# Try add the array of ones and the other most recent array together
sumed_array = sumed_array + one_array_2.T

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [296]:
# Create another array of ones of shape (3, 5)
one_array_3 = np.ones((3,5))

In [297]:
# Subtract the new array of ones from the other most recent array
subtracted_array = sumed_array - one_array_3

In [298]:
# Multiply the ones array with the latest array
multiplied_array = one_array_3*subtracted_array

In [299]:
# Take the latest array to the power of 2 using '**'
powered_array = multiplied_array **2

In [300]:
# Do the same thing with np.square()
np.square(multiplied_array)

array([[ 25.,   4.,  16.,  49.,  64.],
       [  9.,   1.,  16.,   4.,  64.],
       [ 16.,   4.,  36.,  36., 100.]])

In [301]:
# Find the mean of the latest array using np.mean()
np.mean(multiplied_array)

4.8

In [302]:
# Find the maximum of the latest array using np.max()
np.max(multiplied_array)

10.0

In [303]:
# Find the minimum of the latest array using np.min()
np.mean(multiplied_array)

4.8

In [304]:
# Find the standard deviation of the latest array
np.std(multiplied_array)

2.5612496949731396

In [305]:
# Find the variance of the latest array
np.var(multiplied_array)

6.5600000000000005

In [306]:
# Reshape the latest array to (3, 5, 1)
multiplied_array.reshape(3,5,1)

array([[[ 5.],
        [ 2.],
        [ 4.],
        [ 7.],
        [ 8.]],

       [[ 3.],
        [ 1.],
        [ 4.],
        [ 2.],
        [ 8.]],

       [[ 4.],
        [ 2.],
        [ 6.],
        [ 6.],
        [10.]]])

In [307]:
# Transpose the latest array
multiplied_array.T

array([[ 5.,  3.,  4.],
       [ 2.,  1.,  2.],
       [ 4.,  4.,  6.],
       [ 7.,  2.,  6.],
       [ 8.,  8., 10.]])

What does the transpose do?

In [308]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_1 = np.random.randint(low = 0, high=10,size=(3,3))
array_2 = np.random.randint(low = 0, high=10,size=(3,2))

In [309]:
# Perform a dot product on the two newest arrays you created
result_1 = array_1.dot(array_2)

In [310]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_1 = np.random.randint(low = 0, high=10,size=(4,3))
array_2 = np.random.randint(low = 0, high=10,size=(4,3))

In [311]:
# Perform a dot product on the two newest arrays you created
result_2 = array_1.dot(array_2.T)

It doesn't work. How would you fix it?

In [312]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [313]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_1 = np.random.randint(low = 0, high=10,size=(3,6))
array_2 = np.random.randint(low = 0, high=10,size=(3,6))

In [314]:
# Compare the two arrays with '>'
array_1 > array_2

array([[ True, False, False, False, False,  True],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False,  True]])

What happens when you compare the arrays with `>`?

In [315]:
# Compare the two arrays with '>='
array_1 >= array_2

array([[ True, False, False, False, False,  True],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False,  True]])

In [316]:
# Find which elements of the first array are greater than 7
array_1 > 7

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True]])

In [317]:
# Which parts of each array are equal? (try using '==')
array_1 == array_2

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [318]:
# Sort one of the arrays you just created in ascending order
np.sort(array_1)

array([[0, 1, 6, 6, 7, 7],
       [0, 2, 2, 4, 5, 7],
       [0, 2, 2, 4, 4, 9]])

In [319]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_1)

array([[2, 1, 3, 4, 0, 5],
       [5, 1, 4, 0, 3, 2],
       [3, 0, 2, 1, 4, 5]], dtype=int64)

In [320]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_1[1])

2

In [321]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_1[1])

5

In [322]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_1,axis=1)

array([0, 2, 5], dtype=int64)

In [323]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_1,axis=0)

array([2, 0, 0, 2, 1, 1], dtype=int64)

In [324]:
# Create an array of normally distributed random numbers
normalized_array = np.random.normal(size=(2,3))
normalized_array

array([[-1.46696789,  0.89262947, -0.10525713],
       [-0.95534644, -0.41476463, -1.39874088]])

In [325]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even_array = np.linspace(1,100,10)
even_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.